kind: pipeline
type: docker
name: build-publish-image-tag

trigger:
  branch:
  - harness
  event:
  - tag

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: "registry.swisstxt.ch/stxt-proj-cloud-tools/gitbook-visitorauth"
    registry: registry.swisstxt.ch
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: docker
name: build-publish-image-pullrequest

trigger:
  event:
  - pull_request

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: "registry.swisstxt.ch/stxt-proj-cloud-tools/gitbook-visitorauth"
    registry: registry.swisstxt.ch
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - "${DRONE_COMMIT_BRANCH}"
      - "${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}"

- name: notify-cd
  image: plugins/webhook
  environment:
    CD_APPLICATION:
      from_secret: cd_application
  settings:
    urls:
      from_secret: cd_webhook_url
    content_type: application/json
    template: |
      {
        "application": "${CD_APPLICATION}",
        "parameters": {
          "pr_name": "${DRONE_COMMIT_BRANCH}",
          "image_tag": "${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
        }
      }
