kind: pipeline
type: docker
name: build-publish-image-tag

environment:
  CONTAINER_REGISTRY:
    from_secret: container_registry
  CONTAINER_REGISTRY_PROJECT:
    from_secret: container_registry_project
  CD_WEBHOOK_URL:
    from_secret: cd_webhook_url
  CD_APPLICATION:
    from_secret: cd_application

trigger:
  branch:
  - harness
  event:
  - tag

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_PROJECT}/gitbook-visitorauth
    registry: ${CONTAINER_REGISTRY}
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: docker
name: build-publish-image-pullrequest

trigger:
  event:
  - pull_request

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ${CONTAINER_REGISTRY}/${CONTAINER_REGISTRY_PROJECT}/gitbook-visitorauth
    registry: ${CONTAINER_REGISTRY}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
- name: notify-cd
  image: plugins/webhook
  settings:
    urls: ${CD_WEBHOOK_URL}
    content_type: application/json
    template: |
      {
        "application": "${CD_APPLICATION}"
        "parameters": {
          "pr_name": "${DRONE_COMMIT_BRANCH}",
          "image_tag": "${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
        }
      }
